### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by frenchja** [julianlam/nodebb-plugin-emailer-mailgun#11]
This plugin may no longer work with `v1.4.2`. I believe it's missing the configuration panel:

![screen shot 2017-02-04 at 4 35 44 pm](https://cloud.githubusercontent.com/assets/720035/22622140/5f612b20-eaf8-11e6-9d5f-eb8bcf51b5ff.png)

Additionally, the Email configuration tab under "Settings" only displays the Gmail Routing info.

# Info

```
info: Active plugins:
         - nodebb-plugin-composer-default
         - nodebb-plugin-markdown
         - nodebb-plugin-mentions
         - nodebb-widget-essentials
         - nodebb-rewards-essentials
         - nodebb-plugin-soundpack-default
         - nodebb-plugin-emoji-extended
         - nodebb-plugin-emoji-one
         - nodebb-plugin-spam-be-gone
         - nodebb-plugin-desktop-notifications
         - nodebb-plugin-dbsearch
         - nodebb-plugin-emailer-mailgun
```

```
nodebb-plugin-emailer-mailgun: 1.0.2
```

**Comment by katel** [comment]
Have you rebuilt the templates by running  ./nodebb build? After a restart, the Mailgun menu item should appear in the Plugins menu.

**Comment by julianlam** [comment]
This is likely the correct answer @frenchja , let me know if not.
