### ISSUE TITLE
Manually copied emailer-mailgun.tpl to correct location

### ISSUE THREAD

**Issue by imylomylo** [julianlam/nodebb-plugin-emailer-mailgun#13]
Hi!

I'm testing out NodeBB and this plugin and tried to configure it but got a sic, "template not found in directory" error in the browser.

To remedy I copied
NodeBB/node_modules/nodebb-plugin-emailer-mailgun/templates/admin/plugins/emailer-mailgun.tpl
to
NodeBB/build/public/templates/admin/plugins/

NodeBB v1.5.1
Cheers

**Comment by Jop-V** [comment]
I'm on v1.5.3 and I got no error at all, it just kept loading indefinitely. This did fix it though, thanks!

**Comment by julianlam** [comment]
Perhaps nodebb build was not run.

**Comment by Jop-V** [comment]
Argh, yes that was it. A message "you have activated plugins that need to be built" would be nice though, just like the "restart required" message.

**Comment by julianlam** [comment]
Glad to hear it. It's an ongoing concern, and am looking for ways to better communicate this to end users.

Hitting "restart" instead of "reload" builds files, though, so that should be usable instead of running`./nodebb build` explicitly.

**Comment by Jop-V** [comment]
I did `./nodebb restart` multiple times

**Comment by julianlam** [comment]
Actually (and this goes to show how confusing it is...), a `./nodebb restart` **doesn't** build, but hitting the "Restart" button in the admin panel **does** build.
