### ISSUE TITLE
'from' parameter is not a valid address

### ISSUE THREAD

**Issue by DThink** [julianlam/nodebb-plugin-emailer-mailgun#17]
hello, i receive this error when i try to send a confirmation email to a user

`error: [emailer.mailgun] ('from' parameter is not a valid address. please check documentation)
`
i just solved changing the variable `data.from` with `server.domain`

![rsz_screenshot_from_2019-10-23_19-23-47](https://user-images.githubusercontent.com/18085313/67418618-6c8f2f00-f5cb-11e9-9bfe-769ea4fa2fd6.jpg)

**Comment by julianlam** [comment]
From core: `from: meta.config['email:from'] || 'no-reply@' + getHostname(),`

Double-check what value you set in your ACP config for the "From" value. Chances are it's not in a format that Mailgun likes..
