### ISSUE TITLE
unable to config mailgun, the setting page hangs

### ISSUE THREAD

**Issue by lslzl3000** [julianlam/nodebb-plugin-emailer-mailgun#19]
tried nodebb 1.16 and 1.18
the plugin can install and active, but unable to open the setting page, it hangs forever with loading bar

**Comment by julianlam** [comment]
Did you run `./nodebb build`?

**Comment by lslzl3000** [comment]
`build` for many times and still not working yesterday
But I don't know why, it's working today~~ maybe something wrong with the network

I will close this issue, thanks
