### ISSUE TITLE
NPM advises critical issues in dependencies

### ISSUE THREAD

**Issue by T3P3** [julianlam/nodebb-plugin-emailer-mailgun#20]
The last few times upgrading NodeBB I noticed npm advising using npm audit to review some dependencies with issues. I finally had a chance to do that with the upgrade to 1.18.6, there are a couple of critical issues which can apparently be fixed with "npn audit fix --force" but that will "nodebb-plugin-emailer-mailgun@0.2.1" which is clearly not a good idea.

The references issues are:
https://github.com/advisories/GHSA-9j49-mfvp-vmhm
https://github.com/advisories/GHSA-4c7m-wxvm-r7gc
https://github.com/advisories/GHSA-pc5p-h8pf-mvwp
https://github.com/advisories/GHSA-8w57-jfpm-945m

Is this something that can be fixed in a future version of the plugin?

**Comment by julianlam** [comment]
Have published v1.1.0, can you try with that version and let me know if you are able to send emails?

I changed the underlying dependency that connects with Mailgun, so it requires some testing.

**Comment by T3P3** [comment]
v1.1.0 appears to be working well with mailgun in my setup. Thanks!

**Comment by nodebb-misty** [comment]
Great! Thanks for closing the loop on this :)
