### ISSUE TITLE
Not showing up in APC packages due to new packaging rules in 0.7.3

### ISSUE THREAD

**Issue by azariah001** [julianlam/nodebb-plugin-emailer-mailgun#5]
I can't imagine this plugin not working as stands with 0.7.3 as opposed to 0.7.2 but new users installing NodeBB will not see this package or be able to update until compatibility is confirmed with the new version and the rule added to the package.json file.

See https://community.nodebb.org/topic/6298/nodebb-v0-7-3 for details.

**Comment by julianlam** [comment]
:y:

**Comment by julianlam** [comment]
err... :+1:

**Comment by azariah001** [comment]
Just an FYI and so that other users scratching there heads know what's going on. :smile: took me awhile to figure it out. Been configuring an install over the past 3 days sooo it was weird having over half the plugins including this one go poof.

**Comment by julianlam** [comment]
Yes, that is a concern. It's tough to strike a balance between showing many plugins, and minimizing the number of incompatible plugins. 

We may add back in an option to show all plugins (even ones that aren't marked as compatible).

**Comment by azariah001** [comment]
:) That would be nice :) at least until you make breaking changes (hopefully not until 0.8.x) :P

**Comment by julianlam** [comment]
Yeah, that's the idea. There should be no breaking changes to the 0.7.x
branch, so you can trust it from that point of view (theoretically, anyway)
