### ISSUE TITLE
Installed mailergun plugin

### ISSUE THREAD

**Issue by kdrdgn** [julianlam/nodebb-plugin-emailer-mailgun#6]
Although installed mailergun plugin and apikey api mail, "Send Test Mail" doesnt working

**Comment by cubehouse** [comment]
I had this issue when I installed the plugin via "npm install nodebb-plugin-emailer-mailgun"
On the plugins screen I get this oddity:
Mailgun plugin: "Installed 1.0.0 | Latest 0.4.3"

However, if I uninstall the plugin and install via the web interface, it now works and installs version 0.4.3 correctly.

I need to deploy plugins on my forum via npm, so could this get resolved? I'm not sure what NodeBB does differently via the web interface to assist here.

**Comment by cubehouse** [comment]
To confirm that 1.0.0 is the latest intended version:
$ npm info nodebb-plugin-emailer-mailgun
...
'0.4.3': '2015-09-18T18:37:24.361Z',
'1.0.0': '2015-09-24T14:20:55.343Z' 
...

If I install 0.4.3, it works fine in NodeBB 0.8 (this is what I'm doing now, but this shouldn't be required):
$ npm install nodebb-plugin-emailer-mailgun@0.4.3

So has 1.0.0 broken something in 0.8? Was 1.0.0 intended for the upcoming 0.9 release perhaps?

**Comment by julianlam** [comment]
@cubehouse That's correct, the v1.0.0 line is only compatible with the v0.9.x branch. Sorry for the delay in responding :smile:
